## This code can be used to cache the inverse of a matrix instead of having to compute
## it repeatedly. 


## The function creates a special matrix which is a list containing a function to-
## Set the value of the matrix, Get the value of the matrix 
## Set the value of the Inverse, Get the value of the Inverse 

makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
  set <- function(y) {
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setinverse <- function(solve) m <<- solve
  getinverse <- function() m
  list(set = set, get = get,
       setinverse = setinverse,
       getmean = getinverse)
  
}


##This function computes the inverse of the matrix generated by the makeCacheMatrix function

cacheSolve <- function(x, ...) {
  ## Return a matrix that is the inverse of 'x'
  m <- x$getinverse()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data, ...)
  x$setinverse(m)
  m
}
